package compiler

import ASTB.AffBool
import ASTB.Dir

/**
 * stores information about one loop generated by codegen, for proper display
 *
 * @param affects
 * @param pipelined
 */
class Lop(val dir: Option[Dir], val bitSize: Int, val affects: List[Instr], val pipelined: List[Instr], val compiled: List[AffBool]) {
  override def toString = "" + bitSize

}


//class BoolLop(affect:AffBool) extends Lop(List(affect),List(),1) {
